name: CI - SuperBiblio

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le code
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Compiler le projet
        run: mvn compile

      - name: Lancer les tests
        run: mvn test

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Cloner le code
        uses: actions/checkout@v3

      - name: Se connecter à Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construire l’image Docker
        run: docker build -t jpmercier2/superbiblio .

      - name: Pousser sur Docker Hub
        run: docker push jpmercier2/superbiblio